# Generated by Django 2.1.7 on 2019-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment_author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Author',
            field=models.TextField(default=0, max_length=25, verbose_name='Anonymous'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Text',
            field=models.TextField(default=0, max_length=150, verbose_name='Something'),
        ),
    ]
